### ISSUE TITLE
UI Issues and Item Descriptions

### ISSUE THREAD

**Issue by MarcaiDM** [DerDiemen/eclipsephase#22]
Hi there, just made the switch from Roll20 and gotta say I'm very impressed with your module

I am having a couple of UI issues that I wondered if you could have a look at, though? For example, every dropdown menu is actually blank until I mouse-over, which seems to invaidate the ease-of-use of such a feature to begin with. 
![image](https://user-images.githubusercontent.com/109797483/180419508-7eed1b63-03a4-4596-b7c1-254688661e3a.png)

Additionally, writing custom traits seems a bit of a bother, as I can't actually select the "Description" tab  to begin typing. 
![image](https://user-images.githubusercontent.com/109797483/180419751-e96a2ae0-6d07-4cb9-b9f0-ad0423cb7fdf.png)

Lastly, Im wanting to use Monk's Enhanced Journal, but finding that a lot of the base colours seem to clash with those used by MEJ. Not sure if this would be too tricky to fix, especially with it being compatability with another mod. Note the black-on-black title, the white-on-white description in the tab on the right, the barely visible icons above the word "picture".
![image](https://user-images.githubusercontent.com/109797483/180420191-d53ef141-a1cf-4f08-8fdf-9e38b70fdec1.png)

Lastly, as a suggestion for a feature; is there any chance of having both a short description (as is currently used) and a long one? One of the features I've loved in Roll20's Eclipse Phase module was having both, so that players can have the at-a-glance functionality for common use, but also the full description for their mental health conidtions, or the extensive uses of a complex item such as a Covert Operations Tool right there in their inventory. 

Thankyou again for all of your work!

**Comment by DerDiemen** [comment]
Hey Marcai,
Sorry for coming back to you that late. So first things first:

The problem you're experiencing with the dropdowns has already been fixed by another player. I'll update this shortly

Regarding the description of custom traits, I'll have a closer look into this shortly.

The feature request about the long and short description is possible. I'll have a look into this.

A remark from my side: I'm currently incredibly busy with trying to figure out how to translate the system for Foundry version 10. While Foundry offers a grace period it's a bit tricky currently, as they've changed the whole file system again. Difficult for me as a newbie ;) 

At this point I'm unfortunately unable to offer any support for other modules, as they're many and I'm only one person I'm afraid. I might revisit this at a later point in time, but for now I fear, that I cannot really help you out here :( Sorry for that.

All the best

Diemen

**Comment by Animelored** [comment]
Hello, what is the fix that the player/use has created? Can you share it, as I am also running a game and would like to fix it, as it has led to confusion with several players.

**Comment by DerDiemen** [comment]
Hey Animelored,

The CSS problem should be already solved by now. You just need to use the latest release.

**Comment by Animelored** [comment]
Hello, thanks for the response. 
I am still seeing this, do I need to be on Foundry Version 10? I have updated the module to 6.3.2 already.
![image](https://user-images.githubusercontent.com/106208538/186356894-ba0c5c21-ae97-46b1-ab1e-01a99c0ea5fc.png)

**Comment by DerDiemen** [comment]
Hey Animelored,

Has this been fixed for you now? In my test version of Foundry 10 all looked good.

**Comment by DerDiemen** [comment]
All of the above should be covered with the latest update. Please feel free to report any new visual challenge you run into!

- closed
